export const players = {
    "teams": [
      {
        "teamName": "Chennai Super Kings",
        "players": [
          "Ruturaj Gaikwad (captain)",
          "Mahendra Singh Dhoni",
          "Moeen Ali",
          "Deepak Chahar",
          "Tushar Deshpande",
          "Shivam Dubey",
          "Rajvardhan Hangarkar",
          "Ravindra Jadeja",
          "Ajay Mandal",
          "Mukesh Chaudhary",
          "Ajinkya Rahane",
          "Sheikh Rashid",
          "Mitchell Santner",
          "Simarjeet Singh",
          "Nishant Sindhu",
          "Prashant Solanki",
          "Mahish Tikshina",
          "Rachin Ravindra",
          "Shardul Thakur",
          "Daryl Mitchell",
          "Sameer Rizvi",
          "Mustafizur Rahman",
          "Avnish Rao Aravali",
          "Devon Conway (injured)",
          "Matheesha Pathirana (withdrawn)"
        ]
      },
      {
        "teamName": "Mumbai Indians",
        "players": [
          "Hardik Pandya (captain)",
          "Rohit Sharma",
          "Dewald Brevis",
          "Suryakumar Yadav (out of initial matches)",
          "Ishan Kishan",
          "Tilak Verma",
          "Tim David",
          "Vishnu Vinod",
          "Arjun Tendulkar",
          "Shams Mulani",
          "Nehal Wadhera",
          "Jasprit Bumrah",
          "Kumar Karthikeya",
          "Piyush Chawla",
          "Akash Madhwal",
          "Luke Wood",
          "Romario Shepherd",
          "Gerald Coetzee",
          "Shreyas Gopal",
          "Nuwan Thushara",
          "Naman Dheer",
          "Anshul Kamboj",
          "Mohammad Nabi",
          "Shivalik Sharma",
          "Quena Mafaka",
          "Jason Behrendorff (injured)",
          "Dilshan Madushanka (withdrawn)"
        ]
      },
      {
        "teamName": "Royal Challengers Bangalore",
        "players": [
          "Faf du Plessis (captain)",
          "Glenn Maxwell",
          "Virat Kohli",
          "Rajat Patidar",
          "Anuj Rawat",
          "Dinesh Karthik",
          "Suyyash Prabhudesai",
          "Will Jacques",
          "Mahipal Lomror",
          "Karn Sharma",
          "Manoj Bhandge",
          "Mayank Dagar",
          "Vijay Kumar Vaishak",
          "Akash Deep",
          "Mohammed Siraj",
          "Reece Topley",
          "Himanshu Sharma",
          "Rajan Kumar",
          "Cameron Green",
          "Alzarri Joseph",
          "Yash Dayal",
          "Tom Curran",
          "Lockie Ferguson",
          "Swapnil Singh",
          "Sourav Chauhan"
        ]
      },
      {
        "teamName": "Kolkata Knight Riders",
        "players": [
          "Shreyas Iyer (captain)",
          "Nitish Rana",
          "Rinku Singh",
          "Rahmanullah Gurbaz",
          "Phil Salt",
          "Sunil Narine",
          "Suyyash Sharma",
          "Anukul Roy",
          "Andre Russell",
          "Venkatesh Iyer",
          "Harshit Rana",
          "Vaibhav Arora",
          "Varun Chakravarthy",
          "KS Bharat",
          "Chetan Sakariya",
          "Mitchell Starc",
          "Angkrish Raghuvanshi",
          "Ramandeep Singh",
          "Sherfane Rutherford",
          "Manish Pandey",
          "Mujeeb Ur Rahman",
          "Dushmantha Chameera",
          "Saqib Hussain",
          "Jason Roy (injured)",
          "Gus Atkinson (withdrawn)"
        ]
      },
      {
        "teamName": "Gujarat Titans",
        "players": [
          "Shubhman Gill (captain)",
          "David Miller",
          "Matthew Wade",
          "Wriddhiman Saha",
          "Kane Williamson",
          "Abhinav Manohar",
          "Sai Sudarshan",
          "Darshan Nalkande",
          "Vijay Shankar",
          "Jayant Yadav",
          "Rahul Tewatia",
          "Noor Ahmed",
          "Sai Kishore",
          "Rashid Khan",
          "Joshua Little",
          "Mohit Sharma",
          "Azmatullah Omarzai",
          "Umesh Yadav",
          "Shahrukh Khan",
          "Sushant Mishra",
          "Kartik Tyagi",
          "Manav Suthar",
          "Spencer Johnson",
          "Sandeep Warrier",
          "B.R. Sharath",
          "Mohammed Shami (injured)",
          "Robin Minz (withdrawn)"
        ]
      },
      {
        "teamName": "Lucknow Super Giants",
        "players": [
          "KL Rahul (captain)",
          "Quinton de Kock",
          "Nicholas Pooran",
          "Ayush Badoni",
          "Kyle Mayers",
          "Marcus Stoinis",
          "Deepak Hooda",
          "Devdutt Padikkal",
          "Ravi Bishnoi",
          "Naveen Ul Haq",
          "Krunal Pandya",
          "Yudhveer Singh",
          "Prerak Mankad",
          "Yash Thakur",
          "Amit Mishra",
          "Shemar Joseph",
          "Mayank Yadav",
          "Mohsin Khan",
          "Krishnappa Gautam",
          "Shivam Mavi",
          "Arshin Kulkarni",
          "M. Siddharth",
          "Ashton Turner",
          "David Willey",
          "Mohammad Arshad Khan",
          "Mark Wood (injured)"
        ]
      },
      {
        "teamName": "Rajasthan Royals",
        "players": [
          "Sanju Samson (captain)",
          "Jos Buttler",
          "Shimron Hetmyer",
          "Yashasvi Jaiswal",
          "Dhruv Jurel",
          "Ryan Parag",
          "Donovan Ferreira",
          "Krunal Rathore",
          "Ravichandran Ashwin",
          "Kuldeep Sen",
          "Navdeep Saini",
          "Sandeep Sharma",
          "Trent Boult",
          "Yuzvendra Chahal",
          "Avesh Khan",
          "Rovman Powell",
          "Shubham Dubey",
          "Tom Kohler-Cadmore",
          "Abid Mushtaq",
          "Nandre Berger",
          "Tanush Kotian",
          "Prasidh Krishna (injured)",
          "Adam Zampa (withdrawn)"
        ]
      },
      {
        "teamName": "Delhi Capitals",
        "players": [
          "Rishabh Pant (captain)",
          "Praveen Dubey",
          "David Warner",
          "Vicky Ostwal",
          "Prithvi Shaw",
          "Enrique Norcia",
          "Abhishek Porel",
          "Kuldeep Yadav",
          "Axar Patel",
          "Jake Fraser-McGurk",
          "Lalit Yadav",
          "Khaleel Ahmed",
          "Mitchell Marsh",
          "Ishant Sharma",
          "Yash Dhull",
          "Mukesh Kumar",
          "Tristan Stubbs",
          "Ricky Bhui",
          "Kumar Kushagra",
          "Rasik Salam Dar",
          "Jhay Richardson",
          "Sumit Kumar",
          "Shai Hope",
          "Swastik Chikara",
          "Harry Brook (injured)",
          "Lungi Ngidi (withdrawn)"
        ]
      },
      {
        "teamName": "Punjab Kings",
        "players": [
          "Shikhar Dhawan (captain)",
          "Matthew Short",
          "Prabhsimran Singh",
          "Jitesh Sharma",
          "Sikandar Raza",
          "Rishi Dhawan",
          "Liam Livingstone",
          "Atharva Taide",
          "Arshdeep Singh",
          "Nathan Ellis",
          "Sam Curran",
          "Kagiso Rabada",
          "Harpreet Brar",
          "Rahul Chahar",
          "Harpreet Bhatia",
          "Vidwath Kawerappa",
          "Shivam Singh",
          "Harshal Patel",
          "Chris Woakes",
          "Ashutosh Sharma",
          "Vishwanath Pratap Singh",
          "Shashank Singh",
          "Tanay Thiagarajan",
          "Prince Chaudhary",
          "Riley Rossow"
        ]
      },
      {
        "teamName": "Sunrisers Hyderabad",
        "players": [
          "Pat Cummins (captain)",
          "Abdul Samad",
          "Abhishek Sharma",
          "Aiden Markram",
          "Marco Janssen",
          "Rahul Tripathi",
          "Washington Sundar",
          "Glenn Phillips",
          "Sanvir Singh",
          "Heinrich Klaasen",
          "Bhuvneshwar Kumar",
          "Mayank Agarwal",
          "T. Natarajan",
          "Anmolpreet Singh",
          "Mayank Markandey",
          "Upendra Singh Yadav",
          "Umran Malik",
          "Nitish Kumar Reddy",
          "Fazalhaq Farooqui",
          "Shahbaz Ahmed",
          "Travis Head",
          "Wanindu Hasaranga",
          "Jaydev Unadkat",
          "Akash Singh",
          "Jhatved Subramanian"
        ]
      }
    ]
  }

  export default players;